services:
  db:
    hostname: db
    image: pgvector/pgvector:pg16
    ports:
     - 5432:5432
    restart: always
    env_file:
      - ./env/pgsql.env
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./data:/var/lib/postgresql/data